version: '2'
services:
  mysql:
    image: percona/percona-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - /var/lib/mysql
    ports:
       - 3306:3306
  
  app_server1:
    image: arun03nie/my_php_app
    ports: 
       - 8081:80
    links:
       - mysql:mysql
    depends_on:
       - mysql

  app_server2:
    image: arun03nie/my_php_app        
    ports:
       - 8082:80
    links:
       - mysql:mysql
    depends_on:
       - mysql
 
  nginx:
    image: arun03nie/nginx_mysql
    ports:
       - 85:80
    depends_on:
       - mysql
       - app_server1
       - app_server2